### ISSUE TITLE
Latest four builds failed suddenly

### ISSUE THREAD

**Issue by javiertuya** [giis-uniovi/retorch-st-fullteaching#79]
Four PRs with updates failed the build: https://github.com/giis-uniovi/retorch-st-fullteaching/pulls.
Pleaswe, check this and rerun the builds when solved.

**Comment by augustocristian** [comment]
Failure due to a missaligment of the docker version and selenoid: https://github.com/aerokube/selenoid/issues/1340 
Solved, closing the issue when all the builds success.

**Comment by augustocristian** [comment]
I've added an extra container that manages the updates of selenoid selenoid-ui automatically to avoid this type of issues:

``` yaml
  watchtower:
    image: containrrr/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/timezone:/etc/timezone:ro
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  ```

And labeled the containers that I want to automatically update with:

  ```yaml
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
